{% set name = "bkt" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dimo414/bkt/archive/{{ version }}.tar.gz
  sha256: 172c413709dc81ced9dfa2750aaa398864e904d1ed213bd19e51d45d1ff0a8ff

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - bkt --help

about:
  home: https://www.bkt.rs
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Utility for caching the results of shell commands
  dev_url: https://github.com/dimo414/bkt

extra:
  recipe-maintainers:
    - danielnachun
