context:
  version: 0.8.2

package:
  name: bkt
  version: ${{ version }}

source:
  url: https://github.com/dimo414/bkt/archive/${{ version }}.tar.gz
  sha256: d9128a13070ebc564bcc70210062bdd60eb757fd0f5d075c50e9aa7f714c6562

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - bkt --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Utility for caching the results of shell commands
  homepage: https://www.bkt.rs
  repository: https://github.com/dimo414/bkt

extra:
  recipe-maintainers:
    - danielnachun
